config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get 'sa/' => 'station_agent#show_all_models', as: :sa
  get 'sa/initalize_anything' => 'station_agent#initalize_anything', as: :sa_initialize
  get 'sa/:sa_model' => 'station_agent#show_all_of_a_model', as: :sa_model
  get 'sa/:sa_model/:sa_id' => 'station_agent#show_anything', as: :sa_show
  get 'sa/:sa_model/:sa_id/edit' => 'station_agent#edit_anything', as: :sa_edit
  get 'sa/:sa_model/:sa_id/new' => 'station_agent#new_anything', as: :sa_new
  post 'sa/:sa_model/:sa_id' => 'station_agent#update_anything', as: :sa_update

  namespace :api, defaults: {format: :json} do
    resources :timeline_events, only: [:index, :show]
    resources :timelines, only: [:index, :show]
    resources :realms, only: [:index, :show]
    resources :roots, only: [:index, :show]
    resources :characters, only: [:index, :show] do
      get 'search', on: :collection
    end
    resources :houses, only: [:index, :show]
  end

  get '/characters', to: 'welcome#index'
  get '/characters/:id', to: 'welcome#index'
  get '/roots', to: 'welcome#index'
  get '/roots/:id', to: 'welcome#index'
  get '/houses', to: 'welcome#index'
  get '/houses/:id', to: 'welcome#index'
  get '/realms', to: 'welcome#index'
  get '/realms/:id', to: 'welcome#index'

end

app/views/shared/_header.html.erb
<ul class="header-list">
  <li>
    <a href="<%= root_path %>">Home</a>
  </li>
  <li> | </li>
  <li>
    <a href="<%= characters_path %>">Characters</a>
  </li>
  <li> | </li>
  <li>
    <a href="<%= houses_path %>">Houses</a>
  </li>
  <li> | </li>
  <li>
    <a href="<%= realms_path %>">Realms</a>
  </li>
  <li> | </li>
  <li>
    <a href="<%= peerages_path %>">Peerages</a>
  </li>
  <li> | </li>
  <li>
    <a href="<%= timelines_path %>">Timelines</a>
  </li>
</ul>

app/views/shared/_page_numbers.html.erb
<% if @total_pages > 1 %>
  <div class="pagnation-bar">
    <% 1.upto(@total_pages) do |i| %>
      <% if request.query_string.match(/page/) %>
        <% params = request.query_string.gsub(/(page=)(\d+)/, '\1' + i.to_s) %>
      <% else %>
        <% if request.query_string.length > 1 %>
          <% params = request.query_string << "&page=#{i.to_s}" %>
        <% else %>
          <% params = "page=#{i.to_s}" %>
        <% end %>
      <% end %>
      <a class="pagnation-link" href="<%= "#{request.path_info}?#{params}" %> "> <%= i %> </a>
    <% end %>
  </div>
<% end %>