config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get 'sa/' => 'station_agent#show_all_models', as: :sa
  get 'sa/initalize_anything' => 'station_agent#initalize_anything', as: :sa_initialize
  get 'sa/:sa_model' => 'station_agent#show_all_of_a_model', as: :sa_model
  get 'sa/:sa_model/:sa_id' => 'station_agent#show_anything', as: :sa_show
  get 'sa/:sa_model/:sa_id/edit' => 'station_agent#edit_anything', as: :sa_edit
  get 'sa/:sa_model/:sa_id/new' => 'station_agent#new_anything', as: :sa_new
  post 'sa/:sa_model/:sa_id' => 'station_agent#update_anything', as: :sa_update

  namespace :api, defaults: {format: :json} do
    resources :timeline_events, only: [:index, :show]
    resources :timelines, only: [:index, :show]
    resources :realms, only: [:index, :show]
    resources :roots, only: [:index, :show]
    resources :characters, only: [:index, :show] do
      get 'search', on: :collection
    end
    resources :houses, only: [:index, :show]
  end

  get '/characters', to: 'welcome#index'
  get '/characters/:id', to: 'welcome#index'
  get '/roots', to: 'welcome#index'
  get '/roots/:id', to: 'welcome#index'
  get '/houses', to: 'welcome#index'
  get '/houses/:id', to: 'welcome#index'
  get '/realms', to: 'welcome#index'
  get '/realms/:id', to: 'welcome#index'

end

app/controllers/station_agent_controller.rb
class StationAgentController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :sa_on?

  def show_all_models
    Rails.application.eager_load!
    @models = ActiveRecord::Base.descendants.map(&:name)
  end

  def show_all_of_a_model
    @class = params['sa_model'].classify.constantize

    if params['associations_of_model']
      @objects = params['associations_of_model'].classify.constantize.find(params['associations_of_id']).send(params['association']).order(:id)
    else
      @objects = @class.order(:id)
    end

    if @objects.first
      @attributes = @objects.first.attributes.map(&:first)
    end
  end

  def show_anything
    grab_and_set_model_attrs
  end

  def edit_anything
    grab_and_set_model_attrs
  end

  def update_anything
    attribs = params[params['sa_model'].downcase]
    object = params['sa_model'].classify.constantize.find(attribs['id'])
    attribs.each do |attr, val|
      object.send("#{attr}=", val)
    end
    object.save
    redirect_to request.referer
  end

  def new_anything
    @model = params['sa_model'].capitalize.constantize.new

    @attributes = @model.attributes
    @attr_hash = @model.class.columns_hash
    render :show_anything
  end

  def initialize_anything
    @models = ActiveRecord::Base.descendants.map(&:name)
    render :initialize_anything
  end

  private

  def grab_and_set_model_attrs
    @model = params['sa_model'].classify.constantize.find(params['sa_id'])

    @attributes = @model.attributes
    @attr_hash = @model.class.columns_hash

    @associations = {multiple: [], one: []}
    @model.class.reflect_on_all_associations.each do |assoc|
      res = @model.send(assoc.name)
      next unless res.present?

      if res.class.name == assoc.klass.name
        @associations[:one] << {name: assoc.name, model_name: assoc.klass.name, object: res}
      else
        @associations[:multiple] << {name: assoc.name, model_name: assoc.klass.name, count: res.count}
      end
    end
  end

  def get_all_models
    @models = ActiveRecord::Base.descendants.map(&:name)

    @models.reject! do |mod|
      return true if mod == "ActiveRecord::SchemaMigration"
      return false unless @sa_status
      return true if has_yaml_ignore?(@load, 'ignore_models', mod)
    end
  end

  # yaml check

  def sa_on?
    @sa_status = sa_check
  end

  def sa_check
    return true unless has_yaml_file?

    load_yaml

    return false unless authenticate_user!
    return false unless authenticate_method!(params[:action])
    return false unless authenticate_model!(params[:sa_model])
    return false unless authenticate_action_on_model!
  end




  def has_yaml_file?
    File.exist?("#{Rails.root}/config/station_agent.yml")
  end

  def load_yaml
    @yaml = YAML.load_file("#{Rails.root}/config/station_agent.yml")
  end

  def authenticate_user!
    return true unless has_user_valid_check?
    user_valid?
  end

  def authenticate_method!(method)
    return true unless has_yaml_method_override_on? && has_method_override?(method)
  end

  def authenticate_model!(model)
    return true unless has_yaml_model_override_on? && has_model_override?(model)
  end

  def authenticate_action_model!(model, action)
    return true unless has_yaml_model_override_on? && has_model_override?(model)
  end

  def user_valid?
    current_user.send(@yaml[:user_check_method])
  end

  def has_user_valid_check?
    @yaml.has_key?(:user_check_method)
  end

  def has_yaml_method_override_on?
    @yaml.has_key?('model_override')
  end

  def has_method_override?(method)
    @yaml['model_override'].has_key?(method)
  end

  def has_yaml_model_override_on?
    @yaml.has_key?('model_override')
  end

  def has_model_override?(model)
    @yaml['model_override'].has_key?(model)
  end

  def has_yaml_action_on_model_override_on?
    @yaml.has_key?('action_model_override')
  end

  def has_action_on_model_override?(model, action)
    @yaml['action_model_override'].has_key?(model) && @yaml['action_model_override'][model].has_key?(action)
  end

  def has_yaml_attr?(yaml_data, first, array_value = nil)
    if yaml_data.has_key?(first)
      array_value.present? ? yaml_data[first].include?(array_value) : true
    end
  end

  def has_yaml_ignore_columns?(yaml_data)
    has_yaml_ignore?(yaml_data, 'ignore_columns')
  end

  def has_yaml_ignore_model?(yaml_data, model)
    has_yaml_ignore?(yaml_data, 'ignore_models', model)
  end

  def remove_ignored_columns(attributes, yaml_data)
    if yaml_data['ignored_columns'].include?('timestamps')
      yaml_data['ignored_columns'] << 'created_at' << 'updated_at'
    end

    attributes.except!(*yaml_data['ignored_columns'])
    attributes
  end
end

app/helpers/station_agent_helper.rb
module StationAgentHelper
  def sa_link(model, route = :show, params = {})
    params.merge(sa_model: @model.class, sa_id: @model.id)
    if route == :show
      sa_path(params)
    elsif route == :edit
      sa_edit_path(params)
    elsif route == :update
      sa_update_path(params)
    else
      error = 'Invalid route provided to sa_link!'
      if route.is_a?(Symbol)
        error << ' Must be either: :show, :edit, or :update.'
      else
        error << ' It must be a symbol! Instead, a #{route.class} was provided.'
      end
      raise error
    end
  end
end

app/views/station_agent/edit_anything.html.erb
<div class="container">
  <h3>
    <%= "Edit #{@model.class.name}: #{@model.id}" %>
  </h3>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Attr</th>
        <th>Value</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      <%= form_for @model, url: sa_link(@model, :update), method: 'post' do |f| %>
        <% @attributes.each do |attr| %>
          <tr>
            <td> <%= f.label attr.first.to_sym %>:</td>
            <td> <%= f.text_field attr.first.to_sym %></td>
            <td> <%=@attr_hash[attr.first].type%></td>
          </tr>
        <% end %>

    <tr>
        <td colspan="3"> <%= f.submit class: "sa-edit-link" %></td>
      <% end %>
    </tr>
    </tbody>
  </table>
</div>

app/views/station_agent/initialize_anything.html.erb
<ul>
  <% @models.each do |model| %>
      <li>
        <a href="<%= sa_new_path(sa_model: model) %>"><%= model %>:</a>
      </li>
  <% end %>
</ul>

app/views/station_agent/show_all_models.html.erb
<div class="sa-container">
  <table class="sa-table">
    <thead>
      <tr>
        <th>
          Table
        </th>
        <th>
          Count
        </th>
      </tr>
    </thead>
    <% @models.reject{|mod| mod == "ActiveRecord::SchemaMigration"}.each do |model| %>
        <tr>
          <td>
            <a href="<%= sa_model_path(sa_model: model) %>"><%= model %>:</a>
          </td>
          <td>
            <%= model.constantize.count %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/station_agent/show_all_of_a_model.html.erb
<div class="container">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>

        </th>
        <% @attributes.each do |attrib| %>
          <th>
            <%= attrib%>
          </th>
        <%end%>
    </thead>
    <% @objects.each do |object| %>
        <tr>
          <td>
            <a href="<%= sa_show_path(sa_model: object.class.name, sa_id: object.id) %>">Show:</a>
          </td>
          <% @attributes.each do |attrib| %>
          <td>
            <%= object.send(attrib)%>
          </td>
        <%end%>
        </tr>
    <% end %>
  </table>
</div>

app/views/station_agent/show_anything.html.erb
<div  class="container">
  <div>
    <div>
      <h3>Record:</h3>
      <div>
        <a href=<%= sa_link(@model, :edit) %> >Edit</a>
      </div>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>
              Attribute
            </th>
            <th>
              Value
            </th>
          </tr>
        </thead>
        <% @attributes.each do |attr| %>
          <tr>
            <td>
              <%= attr.first %>:
            </td>
            <td>
              <%= attr.last %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div>
      <h3>Belongs To Relationships:</h3>

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>
              Association
            </th>
            <th>
              Object
            </th>
          </tr>
        </thead>
        <% @associations[:one].each do |assoc| %>
          <tr>
            <td>
              <%= assoc[:name] %>:
            </td>
            <td>
              <a href="<%= sa_link(assoc[:object]) %>"><%= assoc[:model_name] %></a>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div>
      <h3>Has Many Relationships:</h3>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>
              Association
            </th>
            <th>
              Object
            </th>
            <th>
              Count
            </th>
          </tr>
        </thead>
        <% @associations[:multiple].each do |assoc| %>
          <tr>
            <td>
              <%= assoc[:name] %>:
            </td>
            <td>
              <a href="<%= sa_model_path(sa_model: assoc[:model_name], associations_of_model: @model.class.name, associations_of_id: @model.id, association: assoc[:name]) %>"><%= assoc[:model_name] %></a>
            </td>
            <td>
              <%= assoc[:count] %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>