config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get 'sa/' => 'station_agent#show_all_models', as: :sa
  get 'sa/initalize_anything' => 'station_agent#initalize_anything', as: :sa_initialize
  get 'sa/:sa_model' => 'station_agent#show_all_of_a_model', as: :sa_model
  get 'sa/:sa_model/:sa_id' => 'station_agent#show_anything', as: :sa_show
  get 'sa/:sa_model/:sa_id/edit' => 'station_agent#edit_anything', as: :sa_edit
  get 'sa/:sa_model/:sa_id/new' => 'station_agent#new_anything', as: :sa_new
  post 'sa/:sa_model/:sa_id' => 'station_agent#update_anything', as: :sa_update

  namespace :api, defaults: {format: :json} do
    resources :timeline_events, only: [:index, :show]
    resources :timelines, only: [:index, :show]
    resources :realms, only: [:index, :show]
    resources :roots, only: [:index, :show]
    resources :characters, only: [:index, :show] do
      get 'search', on: :collection
    end
    resources :houses, only: [:index, :show]
  end

  get '/characters', to: 'welcome#index'
  get '/characters/:id', to: 'welcome#index'
  get '/roots', to: 'welcome#index'
  get '/roots/:id', to: 'welcome#index'
  get '/houses', to: 'welcome#index'
  get '/houses/:id', to: 'welcome#index'
  get '/realms', to: 'welcome#index'
  get '/realms/:id', to: 'welcome#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  has_parents :sex_values => ['M','F'], :current_spouse => true
  belongs_to :primary_house, foreign_key: "house_id", class_name: "House"
  has_many :character_ethnies
  has_many :ethnies, through: :character_ethnies
  has_many :character_houses
  has_many :houses, through: :character_houses
  belongs_to :primary_title,  foreign_key: "title_id", class_name: "Title"
  has_many :titles
  has_many :peerages, through: :titles
  has_many :timeline_event_relateds, as: :related
  has_many :timeline_events, through: :timeline_event_relateds, source: :related, source_type: 'Character'

  after_create :merge_houses
  after_save :genereate_composite_name

  def self.regen_composite_names
    self.find_each do |char|
      char.genereate_composite_name
    end
  end

  def self.search(search_param)
    self.where("native_name LIKE ? OR bailic_name LIKE ? OR real_person LIKE ?", "%#{search_param}%","%#{search_param}%","%#{search_param}%").limit(100)
  end

  def add_married_house(input_house)
    CharacterHouse.create(character_id: self.id, house_id: input_house.id, married_house: true)
    self.save
    self
  end

  def merge_houses
    if self.primary_house.present?
      self.houses << self.primary_house
    end
  end

  def set_composite_name
    name = ''
    name << self.native_name << ' ' if self.native_name
    name << self.bailic_name << ' ' if self.bailic_name
    name << self.nickname << ' ' if self.nickname
    if self.primary_house
      if primary_house.name.match(/Tribe/)
        name << "of #{self.primary_house.name}"
      else
        name << "of House #{self.primary_house.name}"
      end
    end

    if self.married_house.present?
      if self.married_house.name.match(/Tribe/)
        name << " (#{self.primary_house.name})"
      else
        name << " (House #{self.married_house.name})"
      end
    end

    name
  end

  def married_house
    @married_house ||= self.houses.where(character_houses:{married_house: true})[0]
  end

  def limited_ancestors(num_generations)
    count = 0

    ids = []
    generation_ids = parents.compact.map(&:id)
    while (count < num_generations) && (generation_ids.length > 0)
      next_gen_ids = []
      ids += generation_ids

      until generation_ids.empty?
        ids.unshift(generation_ids.shift)
        next_gen_ids += gclass.find(ids.first).parents.compact.map(&:id)
      end
      generation_ids = next_gen_ids
      count += 1
    end
    gclass.where(id: ids)
  end

  def treed
    FamilyTree.new(character: self).descendant_html
  end

  def compact_grandparents
    grandparents.compact
  end

  def compact_great_grandparents
    great_grandparents.compact
  end

  def api_ready
    self.to_json(:methods => [:houses, :composite_name, :primary_house, :father, :mother, :current_spouse, :siblings, :peerages, :parents, :compact_grandparents, :compact_great_grandparents, :uncles_and_aunts, :cousins, :nieces_and_nephews, :children, :grandchildren, :great_grandchildren])
  end

  def genereate_composite_name
    self.update_column(:composite_name, set_composite_name)
  end
end

app/controllers/api/characters_controller.rb
class Api::CharactersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception


  def index
    @characters = Character.order(:composite_name)

    if params['character_ids']
      @characters = @characters.where(id: params['character_ids'].split(','))
    end

    render json: @characters, status: 200
  end


  def show
    render json: Character.find(params['id']).api_ready, status: 200
  end

  def search
    render json: Character.search(params['search']), status: 200
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @characters = Character.where(nil)

    if params['search']
      @characters = @characters.where(
        Character.arel_table['native_name'].matches("%#{params['search']}%").or(
          Character.arel_table['bailic_name'].matches("%#{params['search']}%")
        )
      )
    end

    params['page'] ||= 1
    @limit = params['number'] || 30


    @total_pages = (@characters.count / @limit.to_f).ceil

    offset = ((params['page'].to_i - 1) * @limit.to_i)

    @characters = @characters.limit(@limit).offset(offset)
  end

  def show
    @character = Character.find(params[:id])
    @houseage = @character.primary_house ? " of House #{@character.primary_house.name}" : " "
    @tree = FamilyTree.new(character: @character).descendant_html
  end
end

app/views/characters/index.html.erb
<h2>
  Characters
</h2>
<ul>
  <% @characters.each do |character| %>
    <li>
      <a href="<%= character_path(character) %>"><%= character.composite_name %></a>
    </li>
  <% end %>
</ul>

<%= render "shared/page_numbers" %>

app/views/characters/show.html.erb
<h2>
  <%= "#{@character.bailic_name} #{@character.native_name} #{@houseage}" %>
</h2>

<table class="main-table">
  <thead>
    <tr>
      <th class="left-tab-header">
        Attribute
      </th>
      <th class="right-tab-header">
        Value
      </th>
    </tr>
  </thead>

  <% rows = ['Bailic Name', 'Bailic Translation', 'Native Name', 'Native Translation', 'Nickname'] %>
  <% name_rows = ['Father', 'Mother'] %>

  <% rows.each do |row| %>
    <% if @character.send(row.underscore.gsub(/\s/, '_')) %>
      <tr>
        <td>
          <%= row %>
        </td>
        <td>
          <%= @character.send(row.underscore.gsub(/\s/, '_')) %>
        </td>
      </tr>
    <% end %>
  <% end %>

  <% if @character.primary_house %>
    <tr>
      <td>
        Primary House
      </td>
      <td>
        <a href="<%= house_path(@character.primary_house) %>"> <%= @character.primary_house.name %> </a>
      </td>
    </tr>
  <% end %>

  <% name_rows.each do |row| %>
    <% if @character.send(row.underscore.gsub(/\s/, '_')) %>
      <tr>
        <td>
          <%= row %>
        </td>
        <td>
          <% char = @character.send(row.underscore.gsub(/\s/, '_')) %>
          <% houseage = char.primary_house ? " of House #{char.primary_house.name}" : " " %>
          <a href="<%= character_path(char) %>" > <%= "#{char.bailic_name} #{char.native_name} #{houseage}" %> </a>
        </td>
      </tr>
    <% end %>
  <% end %>

  <% if @character.children.length > 0 %>
    <% @character.children.each do |child| %>
      <tr>
        <td>
          Child
        </td>
        <td>
          <% houseage = child.primary_house ? " of House #{child.primary_house.name}" : " " %>
          <a href="<%= character_path(child) %>" > <%= "#{child.bailic_name} #{child.native_name} #{houseage}" %> </a>
        </td>
      </tr>
    <% end %>
  <% end %>

</table>



<%# family_tree_process(@tree, true).html_safe %>

<!-- <ul class="family_tree">
<% @tree.each do |node| %>
  <% if node.is_a?(Hash) %>

    <li class="parentless">
      <%= "#{node[:bailic_name]}" %>
    </li>
  <% else %>

    <li class="marriage">
     <% if node.length > 0 %>
      <ul class="children">
      <% node.each do |child| %>
        <li class="parented">
          <%= "#{child.first[:bailic_name].strip}" %>
        </li>
        <% if child.length > 1 %>
          <li class="marriage">
            <% if child[1].length > 1 %>
              <ul class="children">
                <li class="parented">
                  <%= "#{child[1].first.first[:bailic_name]}" %>
                </li>
                <li class="parented">
                  <%= "#{child[1].last.first[:bailic_name]}" %>
                </li>
              </ul>
            <% end %>
          </li>
        <% end %>
        <li class="parentless">
          <%= "#{child.last[:bailic_name]}" %>
        </li>
      <% end %>
      </ul>
     <% end %>
    </li>
  <% end %>
<% end %>

</ul>

<ul class="family_tree">
    <li class="parentless">GPA</li>
    <li class="marriage">
        <ul class="children">
            <li class="parented">Uncle</li>
            <li class="marriage"> </li>
            <li class="parentless">Aunt</li>
            <li class="parented">Father</li>
            <li class="marriage">

                <ul class="children">
                    <li class="parented">Son</li>
                    <li class="parented">Daughter</li>
                </ul>
            </li>
            <li class="parentless">Mother</li>
        </ul>
    </li>
    <li class="parentless">GMA</li>
</ul>
%> -->