config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  get 'sa/' => 'station_agent#show_all_models', as: :sa
  get 'sa/initalize_anything' => 'station_agent#initalize_anything', as: :sa_initialize
  get 'sa/:sa_model' => 'station_agent#show_all_of_a_model', as: :sa_model
  get 'sa/:sa_model/:sa_id' => 'station_agent#show_anything', as: :sa_show
  get 'sa/:sa_model/:sa_id/edit' => 'station_agent#edit_anything', as: :sa_edit
  get 'sa/:sa_model/:sa_id/new' => 'station_agent#new_anything', as: :sa_new
  post 'sa/:sa_model/:sa_id' => 'station_agent#update_anything', as: :sa_update

  namespace :api, defaults: {format: :json} do
    resources :timeline_events, only: [:index, :show]
    resources :timelines, only: [:index, :show]
    resources :realms, only: [:index, :show]
    resources :roots, only: [:index, :show]
    resources :characters, only: [:index, :show] do
      get 'search', on: :collection
    end
    resources :houses, only: [:index, :show]
  end

  get '/characters', to: 'welcome#index'
  get '/characters/:id', to: 'welcome#index'
  get '/roots', to: 'welcome#index'
  get '/roots/:id', to: 'welcome#index'
  get '/houses', to: 'welcome#index'
  get '/houses/:id', to: 'welcome#index'
  get '/realms', to: 'welcome#index'
  get '/realms/:id', to: 'welcome#index'

end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  has_many :timeline_timeline_events
  has_many :timeline_events, through: :timeline_timeline_events

  def api_ready
    self.to_json(methods: [:timeline_events])
  end
end

app/controllers/api/timelines_controller.rb
class Api::TimelinesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception


  def index
    render json: Timeline.all, status: 200
  end


  def show
    render json: Timeline.find(params['id']), status: 200
  end

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    params['offset'] ||= 0
    @timelines = Timeline.limit(100).offset(params['offset'])
    @timelines.unshift(Timeline.new(name: 'Master Timeline'))
  end

  def show
    if params['master']
      @timeline = Timeline.new(name: 'Master Timeline')
      @events = TimelineEvent.all
    else
      @timeline = Timeline.find(params['id'])
      @events = @timeline.timeline_events
    end
  end

end

app/views/timelines/index.html.erb
<h1> Timelines </h1>

<table class="main-table">
  <thead>
    <tr>
      <th class="left-tab-header">
        Name
      </th>
      <th class="right-tab-header">
        Description
      </th>
    </tr>
  </thead>

  <% @timelines.each do |timeline| %>
    <tr>
      <td>
        <% if timeline.id.present?%>
          <a href="<%= timeline_path(timeline.path) %>"><%= timeline.name %></a>
        <% else %>
          <a href="<%= timeline_path(0, master: true) %>"><%= timeline.name %></a>
        <% end %>
      </td>
      <td>
        <%= timeline.description %>
      </td>
    </tr>
  <% end %>

</table>

app/views/timelines/show.html.erb
<h1> <%= @timeline.name %> </h1>

<ul>
  <% @events.each do |event| %>
    <li>
      <a href="<%= timeline_event_path(event.id) %>" > <%= "#{event.year} - #{event.name}" %></a>
    </li>
  <% end %>
</ul>